<Project Sdk="Dalamud.NET.Sdk/14.0.2">
  <PropertyGroup>
    <AssemblyName>Ledger</AssemblyName>
    <Version>1.0.1</Version>
    <PackageProjectUrl>https://github.com/Eauldane/Ledger/</PackageProjectUrl>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <Use_DalamudPackager>false</Use_DalamudPackager>
    <Use_Dalamud_ImGui>true</Use_Dalamud_ImGui>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Ledger.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="Data\limited-collectables.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Dalamud.Bindings.ImGui">
      <HintPath>$(DalamudLibPath)Dalamud.Bindings.ImGui.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="DotNet.ReproducibleBuilds" Version="2.0.2" />
  </ItemGroup>
</Project>
